---
# AG06 Mixer - Kubernetes Deployment Configuration
# MANU-Compliant Production Deployment

apiVersion: v1
kind: Namespace
metadata:
  name: ag06-mixer
  labels:
    app: ag06-mixer
    version: "2.0.0"
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ag06-mixer
  namespace: ag06-mixer
  labels:
    app: ag06-mixer
    version: "2.0.0"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ag06-mixer
  template:
    metadata:
      labels:
        app: ag06-mixer
        version: "2.0.0"
    spec:
      containers:
      - name: ag06-mixer
        image: ag06-mixer:2.0.0
        ports:
        - containerPort: 8000
          name: app
        - containerPort: 8080
          name: dashboard
        - containerPort: 9090
          name: metrics
        env:
        - name: AG06_ENV
          value: "production"
        - name: AG06_LOG_LEVEL
          value: "INFO"
        - name: AG06_MONITORING_ENABLED
          value: "true"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - name: config
          mountPath: /app/config
        - name: presets
          mountPath: /app/presets
      volumes:
      - name: config
        configMap:
          name: ag06-config
      - name: presets
        persistentVolumeClaim:
          claimName: ag06-presets-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: ag06-mixer-service
  namespace: ag06-mixer
  labels:
    app: ag06-mixer
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    name: app
  - port: 8080
    targetPort: 8080
    name: dashboard
  - port: 9090
    targetPort: 9090
    name: metrics
  selector:
    app: ag06-mixer

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ag06-config
  namespace: ag06-mixer
data:
  config.yaml: |
    app:
      name: AG06 Mixer
      version: 2.0.0
      environment: production
    audio:
      sample_rate: 48000
      buffer_size: 256
      channels: 2
    midi:
      enabled: true
      device_scan_interval: 5
    monitoring:
      enabled: true
      dashboard_port: 8080
      metrics_port: 9090

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ag06-presets-pvc
  namespace: ag06-mixer
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ag06-mixer-hpa
  namespace: ag06-mixer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ag06-mixer
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ag06-mixer-ingress
  namespace: ag06-mixer
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - ag06-mixer.production.app
    secretName: ag06-mixer-tls
  rules:
  - host: ag06-mixer.production.app
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ag06-mixer-service
            port:
              number: 80