global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'ai-mixer'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - ai-mixer-global
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: (.+)
      - source_labels: [__meta_kubernetes_pod_label_app]
        target_label: app
      - source_labels: [__meta_kubernetes_pod_label_region]
        target_label: region

  - job_name: 'node-exporter'
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - source_labels: [__address__]
        target_label: __address__
        regex: ^(.*):\d+$
        replacement: $1:9100

  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true

  - job_name: 'cloudflare-workers'
    static_configs:
      - targets:
          - 'edge.aimixer.com'
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'health-checks'
    metrics_path: '/health'
    static_configs:
      - targets:
          - 'us-west.aimixer.com'
          - 'us-east.aimixer.com'
          - 'eu-west.aimixer.com'
          - 'ap.aimixer.com'
    scrape_interval: 10s