# AI Mixer Backup System Configuration

# Backup storage settings
backup_root: "./backups"
retention_days: 30

# AWS S3 configuration (optional)
s3_bucket: "ai-mixer-backups"  # Set to null to disable S3
aws_region: "us-west-2"

# Encryption settings
encryption_enabled: true
encryption_key_path: "./backup_encryption.key"

# Components to backup
components:
  - kubernetes_configs
  - docker_images  
  - application_config
  - monitoring_config
  - ssl_certificates

# Kubernetes namespaces to backup
kubernetes_namespaces:
  - ai-mixer-global
  - ai-mixer-monitoring
  - default

# Docker images to backup
docker_images:
  - ai-mixer:latest
  - ai-mixer-ml:latest
  - ai-mixer-edge:latest
  - prom/prometheus:latest
  - grafana/grafana:latest

# Application configuration paths
application_config_paths:
  - deploy_production.sh
  - monitoring/
  - multi_region/
  - edge_computing/workers/
  - mobile_sdks/
  - ml_optimization/
  - API_DOCUMENTATION.md
  - SYSTEM_DOCUMENTATION.md
  - test_results_88.json

# SSL certificate locations
ssl_certificate_paths:
  - /etc/ssl/certs/aimixer.crt
  - /etc/ssl/private/aimixer.key
  - ./certs/

# Backup schedule (cron format)
schedule:
  full_backup: "0 2 * * *"     # Daily at 2 AM
  incremental: "0 */6 * * *"   # Every 6 hours
  cleanup: "0 3 * * 0"         # Weekly cleanup on Sunday at 3 AM

# Recovery settings
recovery:
  default_environment: "production"
  require_approval: true
  approval_timeout_minutes: 30
  
# Notification settings
notifications:
  enabled: true
  email_recipients:
    - devops@aimixer.com
    - backup-alerts@aimixer.com
  slack_webhook: "${SLACK_WEBHOOK_URL}"
  
# Monitoring integration
monitoring:
  prometheus_metrics: true
  grafana_dashboard: true
  alert_on_failure: true
  alert_on_success: false

# Compression settings
compression:
  enabled: true
  algorithm: "gzip"  # gzip, bzip2, xz
  level: 6          # 1-9 compression level

# Verification settings  
verification:
  checksum_algorithm: "sha256"
  verify_after_backup: true
  verify_before_restore: true

# Multi-region backup distribution
multi_region:
  enabled: false
  regions:
    - us-west-2
    - us-east-1
    - eu-west-1
  replication_delay_hours: 4