apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: enterprise-ai-2025
  namespace: argocd
spec:
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: apps
    jsonPointers:
    - /spec/replicas
    kind: Deployment
  info:
  - name: environment
    value: production
  - name: team
    value: platform-engineering
  project: production
  revisionHistoryLimit: 10
  source:
    helm:
      parameters:
      - name: image.tag
        value: 2025.1.0
      - name: replicaCount
        value: '5'
      valueFiles:
      - values-production.yaml
    kustomize:
      images:
      - enterprise-ai:2025.1.0
    path: environments/production
    repoURL: https://github.com/enterprise/k8s-manifests
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
      limit: 5
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
