apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ag06mixer-hpa
  namespace: ag06mixer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ag06mixer-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
---
