apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ag06-api-hpa
  namespace: ag06-production
  labels:
    app.kubernetes.io/name: ag06
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: ag06-deployer
    app.kubernetes.io/part-of: ag06-platform
    app.kubernetes.io/component: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ag06-api
  minReplicas: 3
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      selectPolicy: Min
