name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          cd automation-framework
          pip install flask requests
      - name: Run tests
        run: |
          cd automation-framework
          python test_advanced_patterns_88.py
          python test_enterprise_implementation_88.py
